(require-package 'langtool)
(setq langtool-language-tool-jar "/opt/languagetool/languagetool-commandline.jar")
(global-set-key "\C-x4c" 'langtool-check-buffer)
(global-set-key "\C-x4d" 'langtool-check-done)
(global-set-key "\C-x4n" 'langtool-goto-next-error)
(global-set-key "\C-x4p" 'langtool-goto-previous-error)
(global-set-key "\C-x44" 'langtool-show-message-at-point)
(provide 'init-langtool)
