(require-package 'helm)
(require 'helm-config)
(helm-mode 1)
(require-package 'helm-projectile)
(projectile-global-mode)
(setq projectile-completion-system 'helm)
(helm-projectile-on)
(provide 'init-helm)
